### ISSUE TITLE
Statistics Page

### ISSUE THREAD

**Issue by SephHawkins** [ti-assistant/issues#43]
- [x] ti-assistant/ti-assistant#55
- [x] ti-assistant/ti-assistant#56
- [x] ti-assistant/ti-assistant#57
- [x] ti-assistant/ti-assistant#58
- [x] ti-assistant/ti-assistant#59
- [x] ti-assistant/ti-assistant#60
- [x] ti-assistant/ti-assistant#61
- [x] ti-assistant/ti-assistant#62
